doctrine:
    dbal:
#        url: '%env(resolve:DATABASE_URL)%'
#
#        # IMPORTANT: You MUST configure your db driver and server version,
#        # either here or in the DATABASE_URL env var (see .env file)
#        #driver: 'mysql'
#        #server_version: '5.7'
#
#        # Only needed for MySQL (ignored otherwise)
#        charset: utf8mb4
#        default_table_options:
#            collate: utf8mb4_unicode_ci

        # configure these for your database server

        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
        url: '%env(resolve:DATABASE_URL)%'

#        # configure these for your database server
#        driver: 'pdo_mysql'
#        server_version: '5.7'
#        charset: utf8
#        default_table_options:
#            collate: utf8mb4_unicode_ci
#
#        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
