version: '3'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./:/var/www
        depends_on:
            - postgres
    php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
            - ./:/var/www
            - composer:/root/.composer/cache
        depends_on:
            - postgres
    postgres:
        image: postgres:11.2-alpine
        volumes:
            - ./storage/docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: crazy8
            POSTGRES_PASSWORD: vanbel666
            POSTGRES_DB: urcrm3
        ports:
            - "54321:5432"
volumes:
    composer: